### ISSUE TITLE
联通签到，“日常任务”报错

### ISSUE THREAD

**Issue by 17huiwei** [wangwangit/python_sign#5]
>>>获取登录状态成功！
>>>签到前积分：97
>>>今天已签到！
>>>积分翻倍成功！
>>>签到后积分：97
>>>1G流量日包领取成功！
>>>每日打卡： 今天已打卡
>>>每日浇水： success
>>>签到看视频，下载APP流量奖励任务开始...
>>>签到看视频，下载APP流量奖励任务完成！
Traceback (most recent call last):
  File "/liantong/sign.py", line 208, in <module>
    user.daytask()  # 日常任务
  File "/liantong/sign.py", line 187, in daytask
    print(">>>金币抽奖：", res8.json()['RspMsg'])
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 30 column 1 (char 29)

**Comment by kazeyo666** [comment]
+1  我也是这样

**Comment by 1348182031** [comment]
>>>签到看视频，下载APP流量奖励任务开始...
>>>签到看视频，下载APP流量奖励任务完成！
Traceback (most recent call last):
  File "/home/liantong/liantong/99.py", line 210, in <module>
    user.daytask()  # 日常任务
  File "/home/liantong/liantong/99.py", line 189, in daytask
    print(">>>金币抽奖：", res8.json()['RspMsg'])
  File "/usr/local/lib/python2.7/dist-packages/requests-2.25.0-py2.7.egg/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by wangwangit** [comment]
更新下已解决
