### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by creazytom** [wangwangit/python_sign#9]
C:\Users\Tom\AppData\Local\Programs\Python\Python38\python.exe E:/1/liantong-master/liantong-master/sign.py
>>>获取登录状态成功！
>>>签到前积分：194
>>>今天已签到！
>>>积分翻倍成功！
>>>签到后积分：194
>>>1G流量日包领取成功！
>>>每日打卡： 今天已打卡
>>>每日浇水： success
>>>签到看视频，下载APP流量奖励任务开始...
>>>签到看视频，下载APP流量奖励任务完成！
Traceback (most recent call last):
  File "E:/1/liantong-master/liantong-master/sign.py", line 208, in <module>
    user.daytask()  # 日常任务
  File "E:/1/liantong-master/liantong-master/sign.py", line 187, in daytask
    print(">>>金币抽奖：", res8.json()['RspMsg'])
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1

**Comment by wangwangit** [comment]
你用的是最新的代码么.这块我应该已经屏蔽了
